# Generated by Django 5.1.2 on 2024-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('YearofBirth', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('PreviousAppointment', models.DateField()),
                ('NextAppointment', models.DateField()),
                ('BloodPressure1', models.IntegerField()),
                ('BloodPressure2', models.IntegerField()),
                ('BloodPressure3', models.IntegerField()),
                ('BloodPressure4', models.IntegerField()),
                ('BloodPressure5', models.IntegerField()),
            ],
        ),
    ]
